### ISSUE TITLE
Error: `Cannot access 'co.daily.CallClientListener' which is a supertype of 'ai.vapi.android.Vapi'`

### ISSUE THREAD

**Issue by robingenz** [VapiAI/android#5]
I get the following error message in Android Studio when I try to listen to the events:

```
Cannot access 'co.daily.CallClientListener' which is a supertype of 'ai.vapi.android.Vapi'. Check your module classpath for missing or conflicting dependencies
```

![grafik](https://github.com/user-attachments/assets/ba51b157-1ab9-4f8f-855d-922a4099b9ae)

What am I doing wrong here?

**Comment by robingenz** [comment]
Does anyone have any ideas on how I can solve this? My customer would like to get started with Vapi.

**Comment by LucasBaccaro** [comment]
You need to install the co.daily dependencies and it will work. 
But when I try to run. Vapi responds forbidden 403 and not explains more :( do you have any solution?

**Comment by abizzaar** [comment]
This is fixed in the newer version (you shouldn't need to install co.daily separately anymore)
```
dependencies {
    // ...
    implementation 'ai.vapi.android:vapi:1.0.7'
}
```

**Comment by abizzaar** [comment]
@LucasBaccaro if you're still getting the 403 error please open another issue for it!
